### ISSUE TITLE
Set Email in XMPP

### ISSUE THREAD

**Issue by KeyideasGlobal** [dbsGen/XEP-0055#2]
Hi ,
could you tell me how emplement - (void)setEmailAddresses:(NSArray *)emails XMPPvCardTemp class.

Thanks in Adv.
Mahendra

**Comment by dbsGen** [comment]
I have no idea, try to vist https://github.com/robbiehanson/XMPPFramework. and open a issue

**Comment by KeyideasGlobal** [comment]
OK cool thanks for reply.

Mahendra
